mode: predict
debug: False
load_ckpt: experiments/vm_quick_baseline_micro20/checkpoint_19.pkl

components:
  data: predict_quick
  transform: predict
  system: vm
  model: vm

writer:
  __target__: vm
  save_dir: tmp_predict_vm_quick_baseline_micro20
  save_name: denoised
