train_transform:
  augments:
    - __target__: sample
      num_samples: 32768
      num_vertex_samples: 1024
    
    - __target__: normalize_pc
    
    - __target__: add_noise
      noise_std_min: 0.005
      noise_std_max: 0.020
    
    - __target__: linear
      scale: [0.8, 1.2]
      rotate_x_range: [-180, 180]
      rotate_y_range: [-180, 180]
      rotate_z_range: [-180, 180]
      scale_p: 0.5
      rotate_p: 0.5
    
    - __target__: patch
      patch_size: 1000
      num_patches: 1
      train_cvm_network: False

validate_transform: &validate_transform
  augments:
    - __target__: sample
      num_samples: 32768
      num_vertex_samples: 1024
    
    - __target__: normalize_pc
    
    - __target__: add_noise
      noise_std_min: 0.005
      noise_std_max: 0.020
    
    - __target__: patch
      patch_size: 1000
      num_patches: 1
      train_cvm_network: False

predict_transform: *validate_transform