mode: predict
debug: False
load_ckpt: experiments/vm/checkpoint_99.pkl

components:
  data: predict_quick
  transform: predict
  system: vm
  model: vm

writer:
  __target__: vm
  save_dir: tmp_predict_quick
  save_name: denoised
