mode: predict
debug: False
load_ckpt: experiments/vm_quick/checkpoint_0.pkl

components:
  data: predict_quick
  transform: predict
  system: vm_quick
  model: vm

writer:
  __target__: vm
  save_dir: results_quick/dataset_test_noisy
  save_name: denoised
